# Generated by Django 4.2.9 on 2024-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_time_trial_time',
            field=models.IntegerField(default=0),
        ),
    ]
