# Generated by Django 4.2.9 on 2024-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('time_trial', 'Time Trial')], default='classic', max_length=11),
        ),
        migrations.AddField(
            model_name='game',
            name='time_left',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('incomplete', 'Incompleted')], default='in_progress', max_length=11),
        ),
    ]
