# Generated by Django 4.2.9 on 2024-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_game', '0002_game_game_type_game_time_left_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_time_trial_time',
            field=models.IntegerField(default=0),
        ),
    ]
