# Generated by Django 4.2.9 on 2024-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_game', '0003_game_max_time_trial_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Climate change fundamentals', 'Climate change fundamentals'), ('Climate change disinformation', 'Climate change disinformation'), ('Climate change communications and narratives', 'Climate change communications and narratives'), ('Media literacy', 'Media literacy')], default='Climate change fundamentals', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('time_trial', 'Time Trial'), ('category', 'Category')], default='classic', max_length=11),
        ),
    ]
