# Generated by Django 4.2.9 on 2024-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_game', '0004_question_category_question_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Climate change fundamentals', 'Climate change fundamentals'), ('Climate change disinformation', 'Climate change disinformation'), ('Climate change communication and narratives', 'Climate change communication and narratives'), ('Media literacy', 'Media literacy')], max_length=50),
        ),
    ]
