# Generated by Django 4.2.9 on 2024-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_max_time_trial_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_time_trial_points',
            field=models.IntegerField(default=0),
        ),
    ]
